#pragma once
#define LUA_MODULE_IMGUI_CDECL 300
#define LUA_MODULE_IMGUI 301
#define LUA_MODULE_MEMORY 302
#define LUA_MODULE_EVENTS 303
#define LUA_MODULE_TIMERS 304
#define LUA_MODULE_CONFIG 306
#define LUA_BASE_MODULE 305
#define RES_LOGO 400
